apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qm8sr481q-nodejs 
  janus-idp.io/tekton: qm8sr481q-nodejs
  backstage.io/kubernetes-id: qm8sr481q-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qm8sr481q-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  